# Configure main menu and social menu
[[social]]
identifier = "home"
name = "1. Home"
url = "/"
[social.params]
icon = "home"
newtab = true

[[social]]
identifier = "About"
name = "3. About"
url = "https://unorthodoxdev.net/about"

[social.params]
icon = "info"
newtab = true

[[social]]
identifier = "comment board"
name = "3. Comments"
url = "https://unorthodoxdev.net/comment"

[social.params]
icon = "comment"
newtab = true

[[social]]
identifier = "github"
name = "4. GitHub"
url = "https://github.com/ofgrenudo/"

[social.params]
icon = "brand-github"
newtab = true
